iex (irm 'https://raw.githubusercontent.com/adoonrat/Autopilot/main/A00_BIOSSettings.ps1')
iex (irm 'https://raw.githubusercontent.com/adoonrat/Autopilot/main/A01_ClearDisk.ps1')
iex (irm 'https://raw.githubusercontent.com/adoonrat/Autopilot/main/A02_Prep_OS.ps1')
iex (irm 'https://raw.githubusercontent.com/adoonrat/Autopilot/main/A03_Prep_Drivers.ps1')
iex (irm 'https://raw.githubusercontent.com/adoonrat/Autopilot/main/A04_Apply_OS.ps1')
iex (irm 'https://raw.githubusercontent.com/adoonrat/Autopilot/main/A05_Apply_Drivers.ps1')
iex (irm 'https://raw.githubusercontent.com/adoonrat/Autopilot/main/A06_Finalization.ps1')
